<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>Async Fetch - Load JSON</title>
    <style>
        body {
            font-family: sans-serif;
        }
    </style>

</head>

<body>
    <h2>Async Fetch - Load JSON File</h2>
    <hr>
    <button id="my-button">Load Data</button>
    <div id="output">Click button to load</div>

    <script>
        document.querySelector("#my-button").onclick = loadJsonFetch;

        // HW
        async function loadJsonFetch() {
            try {
                // await ("stay on this line") until the first promise is resolved, meaning the data has downloaded
                let response = await fetch("data/pet-names.json");

                // If the response is not successful, throw an error
                if (!response.ok) {
                    if (response.status == 404) console.log("Do 404 stuff");
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                // await ("stay on this line") until the second promise is resolved, meaning we now have a JSON object
                let json = await response.json();
                const keyArray = Object.keys(json); // gets the keys
                let html = "";

                for (let k of keyArray) {
                    // loop through the keys and look at the object linked to the specific key
                    const obj = json[k];
                    html += `<h3>${obj.title = obj.title ? obj.title : "No title found"}</h3>`; // ternary operator that checks to see if there is a title
                    html += `<ol>${obj["namelist"].map(item => `<li>${item}</li>`).join('')}</ol>`; //we get the data from obj that is tagged as "namelist"
                }

                document.querySelector("#output").innerHTML = html;
            } catch (e) {
                document.querySelector("#output").innerHTML = `<b>ERROR: ${error}</b>`;
                console.log(`In catch with e = ${e}`);
            }
        }

        // II-A. Simple async/await example (no error handling)
        async function loadJsonFetchA() {
            // await ("stay on this line") until the first promise is resolved, meaning the data has downloaded
            let response = await fetch('https://swapi.dev/api/people/1');

            // await ("stay on this line") until the second promise is resolved, meaning we now have a JSON object
            let json = await response.json();
            console.log(json);
            console.log(json.name);
            console.log(json.homeworld);
            document.querySelector("#output").innerHTML = "check the console";
        }

        // II-B. async/await example with try/catch for error handling
        async function loadJsonFetchB() {
            try {
                // await ("stay on this line") until the first promise is resolved, meaning the data has downloaded
                let response = await fetch('https://swapi.dev/api/people/1');

                // If the response is not successful, throw an error
                if (!response.ok) {
                    if (response.status == 404) console.log("Do 404 stuff");
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                // await ("stay on this line") until the second promise is resolved, meaning we now have a JSON object
                let json = await response.json();
                console.log(json);
                console.log(json.name);
                console.log(json.homeworld);
                document.querySelector("#output").innerHTML = "check the console";
            } catch (e) {
                console.log(`In catch with e = ${e}`);
            }
        }

        // II-C. async/await example with .catch() for error handling
        function loadJsonFetchC() {
            const fetchPromise = async () => {
                // await ("stay on this line") until the first promise is resolved, meaning the data has downloaded
                let response = await fetch('https://swapi.dev/api/people/1');

                // If the response is not successful, throw an error
                if (!response.ok) {
                    if (response.status == 404) console.log("Do 404 stuff");
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                // await ("stay on this line") until the second promise is resolved, meaning we now have a JSON object
                let json = await response.json();
                console.log(json);
                console.log(json.name);
                console.log(json.homeworld);
                document.querySelector("#output").innerHTML = "check the console";
            };

            // Call fetchPromise() and add a .catch() to it,
            // this works because fetchPromise is async and returns a promise
            fetchPromise()
                .catch(e => {
                    console.log(`In catch with e = ${e}`);
                });
        }
    </script>
</body>

</html>